//------------------------------------------------------------------------------
// <auto-generated>
//     Generated manually for SixLabors.ImageSharp on Linux/.NET 9
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace Nolvus.Package.Properties
{
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resources() { }

        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new global::System.Resources.ResourceManager("Nolvus.Package.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        // ------------------- Images -------------------
        internal static Image<Rgba32> mod_def_22 => LoadImage("mod_def_22.png");
        internal static Image<Rgba32> splash_v5 => LoadImage("splash_v5.png");
        internal static Image<Rgba32> splash_v6 => LoadImage("splash_v6.png");

        // ------------------- Raw bytes -------------------
        internal static byte[] NolvusLauncher => File.ReadAllBytes(Path.Combine(AppContext.BaseDirectory, "Resources", "NolvusLauncher.exe"));

        private static Image<Rgba32> LoadImage(string fileName)
        {
            var path = Path.Combine(AppContext.BaseDirectory, "Resources", fileName);
            if (!File.Exists(path))
                throw new FileNotFoundException($"Resource file not found: {path}");

            return Image.Load<Rgba32>(path);
        }
    }
}
